### ISSUE TITLE
'During handling of above exception, another exception occurred: get_all_entries_data(args.journal_id)'

### ISSUE THREAD

**Issue by ethanfischer** [ianmcaulay/penzu-export#1]
Hello,

I got this program to run and it seems to be working for about 2 minutes until I run into this error:

`Fetching entry xxxxxxxx
Fetching entry xxxxxxx
Traceback (most recent call last):
  File "/Users/xxxxxxxxxxxx/Repos/penzu-export/export_penzu_data.py", line 120, in get_entry_data
    text_element = get_only_element(driver.find_elements(By.CLASS_NAME, 'cke_inner'))
  File "/Users/xxxxxxxxxxxx/Repos/penzu-export/export_penzu_data.py", line 30, in get_only_element
    raise ValueError(f'Expected length 1, got length {len(lst)} in list {lst}.')
ValueError: Expected length 1, got length 0 in list [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxxxxxxxxx/Repos/penzu-export/export_penzu_data.py", line 171, in <module>
    get_all_entries_data(args.journal_id)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxxxxxxxx/Repos/penzu-export/export_penzu_data.py", line 160, in get_all_entries_data
    entry_data = get_entry_data(driver, entry)
  File "/Users/xxxxxxxxxxxx/Repos/penzu-export/export_penzu_data.py", line 123, in get_entry_data
    text_element = get_only_element(driver.find_elements(By.CLASS_NAME, 'cke_inner'))
  File "/Users/xxxxxxxxxxxx/Repos/penzu-export/export_penzu_data.py", line 30, in get_only_element
    raise ValueError(f'Expected length 1, got length {len(lst)} in list {lst}.')
ValueError: Expected length 1, got length 0 in list [].
`

Seems like it's failing to get the journal id in that exception handling code? But not sure why since it seems to be using it well when running in the beginning.

Using Python 3.13.0 on macos Sequoai 15.1.1 with iTerm2 and homebrew

**Comment by ethanfischer** [comment]
More context: I watched it as things were running and it looks like this error happens after chrome navigates to a 404 'page not found' page.

This happens every time I run the program fyi, eventually
